### ISSUE TITLE
Question: How are lat/lng queries for intersections (etc.) cached?

### ISSUE THREAD

**Issue by palewire** [newsapps/django-boundaryservice#16]

**Comment by onyxfish** [comment]
There is no caching done on the server side, it's expected that you will put varnish or some other caching system in front of the boundaryservice.  That said, because every geo-query tends to be unique (due to lat/lng be parameters), its unlikely that caching is of much benefit.  In general, this sort of system is one in which the benefit of caching is limited.  If you hit the performance limit, more CPU is really the order of the day.

**Comment by palewire** [comment]
Have you done much load testing with a rapid series of unique lat/lng pairs?

**Comment by onyxfish** [comment]
I've done some, but its difficult to quantify because the performance is very dependent on A) the hardware its running on, B) the number of geometries that are indexed, and C) the complexity of the geometries.

If you've got a very large number of complex, overlapping geometries your performance will scale much differently than for a simpler use-case.

That said, our production instance (database is running on an EC2 small with our other sites) has handled bursts of ~50 unique requests with no noticeable impact on our regular operations. (Not enough to set off our Cloudkick alarms.)

**Comment by palewire** [comment]
I'm curious about the "number of geometries" issue. Can that be lessened by restricting a "get all" overlapping geometries request and demanding the user provide a dataset "filter" that is preapplied before the geometric operation?

**Comment by onyxfish** [comment]
Yes, in fact, I strongly recommend that the "sets" parameter is used whenever possible to restrict the universe of geometries that postgis has to perform intersections tests. If you can constrain any individual request to a small number of geometries you will get a lot more mileage out of the system.

There are probably other arbitrary filters you could provide depending on your use case.

**Comment by palewire** [comment]
Closing as stale.
