### ISSUE TITLE
What do you think about load_shapefiles telling stdout what it's up to?

### ISSUE THREAD

**Issue by palewire** [newsapps/django-boundaryservice#20]
Just spit out the basic logging stuff, created this, updated that, did nothing, etc.

**Comment by onyxfish** [comment]
It currently logs with logging, which I would nominally argue is better than printing to stdout. Do you have a reason to change that? You can always tweak your logging config if you're not getting what you need.

**Comment by palewire** [comment]
It's not a big thing, but during my Hello World experiments I didn't get that 'oooh shit, I did it' feeling without a stupid printout. I'm childish like that. And, without knowing the insides very well, I wasnt' sure exactly what happened when I ran it a second time. Did it skip the already-loaded data, or reload it? (Obvs, I figured that out, but it was kind of a mystery to a newbie.)

Another option might be a "verbosity" config in the standard manage.py manner.

**Comment by eyeseast** [comment]
This might be a Django 1.3 issue, since logging config became a centralized thing in the latest version. Try adding this to your LOGGING setting under loggers (so, specifically LOGGING['loggers']):

```
    'boundaries.api.load_shapefiles': {
        'handlers': ['console'],
        'level': 'INFO',
        'formatter': 'simple'
    },
```

Assuming you have the standard logging settings that are created when you start a new project, it should log to stdout (using the 'console' handler).

**Comment by palewire** [comment]
Closing as stale.
